[package]
name = "chat"
version = "0.1.0"
authors = ["Yuki Nagae <yuki.nagae1130@gmail.com>"]

[dependencies]
http-muncher = "0.3.*"
rustc-serialize = "0.3.*"
sha1 = "0.2.*"
byteorder = "0.3.*"

[dependencies.mio]
git = "https://github.com/carllerche/mio"
